# Generated by Django 3.0.6 on 2020-05-14 14:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0003_auto_20200511_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtime',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mealtime',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 14, 7, 16, 380836, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sugarlevel',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 14, 7, 16, 380369, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='CommonMeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('trash', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=30)),
                ('fat', models.IntegerField(blank=True, null=True)),
                ('carbohydrates', models.IntegerField(blank=True, null=True)),
                ('proteins', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'st_common_meals',
                'ordering': ['name'],
            },
        ),
    ]
