# Generated by Django 3.0.6 on 2020-05-14 15:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20200514_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealtime',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 15, 18, 49, 370076, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sugarlevel',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 15, 18, 49, 369629, tzinfo=utc)),
        ),
    ]
