# Generated by Django 3.0.6 on 2020-05-14 15:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20200514_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealtime',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 15, 22, 52, 404216, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sugarlevel',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 15, 22, 52, 403769, tzinfo=utc)),
        ),
    ]
