# Generated by Django 3.0.6 on 2020-05-17 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20200516_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealtime',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sugarlevel',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
